/*
 * File: app/view/MyGridPanel.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyGridPanel', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.companygrid',

    title: 'My Grid Panel',
    store: 'Companies',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'company',
                    flex: 1,
                    text: 'Company'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'price',
                    text: 'Price'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        if (value > 0) {
                            return '<span style="color:green;">' + value + '</span>';
                        } else if (value < 0) {
                            return '<span style="color:red;">' + value + '</span>';
                        }
                        return value;
                    },
                    dataIndex: 'change',
                    text: 'Change'
                }
            ],
            viewConfig: {

            }
        });

        me.callParent(arguments);
    }

});